### ISSUE TITLE
Architecture not supported

### ISSUE THREAD

**Issue by davthu** [solugo/gradle-nodejs-plugin#16]
Our gradle build task fails on this plugin when building on a 64bit macOS High Sierra.

```
> Architecture not supported
```

**Comment by frederic-kneier** [comment]
Which version are you using? A bug with handling of macOS has been recently fixed. Verison 0.6.0 should work.

**Comment by davthu** [comment]
I think we use an older version, this is what i can see:

```
  dependencies {
    classpath "gradle.plugin.de.solugo.gradle:gradle-nodejs-plugin:0.2.1"
  }
```

**Comment by frederic-kneier** [comment]
Please update to:

```
dependencies {
  classpath "de.solugo.gradle:gradle-nodejs-plugin:0.6.0"
}
```

**Comment by frederic-kneier** [comment]
Did it work?
