### ISSUE TITLE
Running tasks fails on Windows

### ISSUE THREAD

**Issue by sschuberth** [solugo/gradle-nodejs-plugin#18]
After applying the plugin and running `yarnInstall` on Windows I'm getting

```
$ ./gradlew :reporter-web-app:yarnInstall
Configuration on demand is an incubating feature.
> Task :reporter-web-app:yarnInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reporter-web-app:yarnInstall'.
> execCommand == null!
```

The same command works on Linux, though. Is there maybe an issue within the [resolveCommand()](https://github.com/solugo/gradle-nodejs-plugin/blob/3a0f70d2de213b82ce3ba35e440e61b67c4bc45d/src/main/groovy/de/solugo/gradle/nodejs/NodeJsTask.groovy#L84) logic?

PS: You could add AppVeyor for Windows CI to guard against breaking Windows support (provided there are proper tests being run).

**Comment by frederic-kneier** [comment]
Sorry for the late reply. Problem is the extraction of the nodejs zip file. Fix will be suplied shortly

**Comment by sschuberth** [comment]
Thanks!
