### ISSUE TITLE
How to import the plugin ?

### ISSUE THREAD

**Issue by pilak** [solugo/gradle-nodejs-plugin#2]
Hello,
I just would like to know how to import the plugin.
Shall I have to compile it before ?
Thanks for advise

**Comment by frederic-kneier** [comment]
Hi. The plugins are already published to the Gradle plugin repository. 

https://plugins.gradle.org/plugin/de.solugo.gradle.nodejs

https://plugins.gradle.org/plugin/de.solugo.gradle.webpack

I will try to describe it more clearly in the README with the next update.

**Comment by pilak** [comment]
Ok thank you,
I also don't understand how to use it. May you give a concrete example of command line please ?
Regards

**Comment by pilak** [comment]
PS : for example, if I write the command below :
```
gradle nodeindex
```
I get the error although I have a file in the folder called index.js :
```
Error: Cannot find module '/home/pilak/project/ndex.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

```

**Comment by frederic-kneier** [comment]
This seems to be a casing problem. If you want to start index.js try:
<pre>
gradle nodeIndex
</pre>

**Comment by pilak** [comment]
works better :)
Thank you Frederic

**Comment by frederic-kneier** [comment]
Documentation has been updated
