### ISSUE TITLE
External registry

### ISSUE THREAD

**Issue by davthu** [solugo/gradle-nodejs-plugin#21]
Is it possible to configure the plugin to accept external registry for org scoped packages? I can't verify that a local .npmrc is working.

```
#.bashrc
//registry.npmjs.org/
@org:registry=https://localhost:8081/nexus/content/repositories/npm-internal
```

**Comment by frederic-kneier** [comment]
Where is your npmrc located?

**Comment by davthu** [comment]
Next to package.json. However, the problem was the registry url, not in this plugin. Thank you for quick response.

```
registry=https://localhost:8081/nexus/content/repositories/npm-all
```
