### ISSUE TITLE
Multiple Node installations

### ISSUE THREAD

**Issue by davthu** [solugo/gradle-nodejs-plugin#23]
We have an issue currently with a Gradle Multi project that have their own `build.gradle` scripts with different Node versions.
Since this is Bitbucket building (pipelines) it will download the first Node version encountered and keep that version over the builds. Therefore some projects fail.

My question is if it is possible to force installation of a new Node version between Gradle sub project builds?

**Comment by frederic-kneier** [comment]
This is currently not possible. But I might be able to allow multiple versions of NodeJs in one gradle session. I will have a look right away

**Comment by frederic-kneier** [comment]
I can not reproduce the problem with version 0.6.2:

build.gradle:

    plugins {
        id 'de.solugo.gradle.nodejs' version '0.6.2'
    }
    
    nodejs {
        version = '8.11.3'
    }

sub/build.gradle:

    plugins {
        id 'de.solugo.gradle.nodejs'
    }
    
    nodejs {
        version = '8.11.0'
    }

```
> Task :npmVersion
Extracting NodeJs to C:\Users\Frederic\.nodejs\8.11.3
{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.11.3',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.54',
  zlib: '1.2.11' }

> Task :sub:npmVersion
Extracting NodeJs to C:\Users\Frederic\.nodejs\8.11.0
{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.11.0',
  openssl: '1.0.2o',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.50',
  zlib: '1.2.11' }
```

**Comment by davthu** [comment]
We do not specify the plugin version which might be a cause for error?

`apply plugin: "de.solugo.gradle.nodejs"`

**Comment by davthu** [comment]
We do not specify a version of your plugin. Do you think that might cause the problem?

```
apply plugin: "de.solugo.gradle.nodejs"

nodejs {
  version = '10.15.0'
}
```

**Comment by frederic-kneier** [comment]
The actual version should be specified in the "buildScript" section. Did you specify another NodeJs version in the submodules?

**Comment by frederic-kneier** [comment]
Is this still an issue?

**Comment by davthu** [comment]
No, we use the same Node version across the project now.
