### ISSUE TITLE
How to set the workDir of the plugin

### ISSUE THREAD

**Issue by davthu** [solugo/gradle-nodejs-plugin#8]
I need to specify a subdirectory as the working directory for the gradle task that runs the npm task. Is that possible?

**Comment by frederic-kneier** [comment]
This would affect the path of the node_modules folder as well. Is this what you would expect?

**Comment by davthu** [comment]
Yes, the package.json file is located in a subfolder from where the gradle task is run from.

**Comment by frederic-kneier** [comment]
I will try to add that option

**Comment by davthu** [comment]
I solved it with a package.json file in the root directory that defines tasks as aliases to child tasks like this:

```
{    
   "scripts": {
        "postinstall": "cd subdir && npm install",
        "build": "cd subdir && npm run build",
        "test": "cd subdir && npm test"
    }
}
```

**Comment by frederic-kneier** [comment]
that works for those scripts only. You can now update to version 0.5.1 and add the following configuration:
```groovy
nodejs {
  rootPath = "subdir"
}
```
